#!/usr/bin/env python3
"""Sync msitarzewski/agency-agents into agency-agents-<division> Spec Kit extensions.

For each division listed in the upstream ``divisions.json`` this script generates
an ``agency-agents-<division>/`` extension whose commands are the division's
agent personality files. It also rebuilds ``catalog.json`` (preserving any
non-division extensions such as ``aide``, ``extensify``, ``presetify`` and
``agency-agents-sync``) and refreshes a managed table in the top-level README.

Usage:
    python3 scripts/sync-agency-agents.py            # clone upstream @ main
    python3 scripts/sync-agency-agents.py --ref v1.2 # clone a specific ref
    python3 scripts/sync-agency-agents.py --src /path/to/agency-agents  # local

Only the Python standard library is required.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

UPSTREAM_URL = "https://github.com/msitarzewski/agency-agents.git"
UPSTREAM_HOME = "https://github.com/msitarzewski/agency-agents"

REPOSITORY = "https://github.com/mnriem/spec-kit-extensions"
RAW_CATALOG_URL = (
    "https://raw.githubusercontent.com/mnriem/spec-kit-extensions/main/catalog.json"
)
AUTHOR = "spec-kit-community"
VERSION = "1.0.0"
SPECKIT_REQUIRES = ">=0.2.0"
PREFIX = "agency-agents"

README_BEGIN = "<!-- BEGIN agency-agents (generated by scripts/sync-agency-agents.py) -->"
README_END = "<!-- END agency-agents (generated by scripts/sync-agency-agents.py) -->"


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #
def yaml_dq(value: str) -> str:
    """Return ``value`` as a double-quoted YAML/JSON-safe scalar."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def collapse_ws(value: str) -> str:
    return re.sub(r"\s+", " ", value).strip()


def parse_frontmatter(text: str):
    """Return (metadata_dict, body) for a markdown file with YAML frontmatter.

    Only the small subset of YAML used by agency-agents files (``key: value``)
    is parsed, so no third-party dependency is needed. Returns (None, text) if
    the file has no frontmatter.
    """
    if not text.startswith("---"):
        return None, text
    lines = text.splitlines()
    if lines[0].strip() != "---":
        return None, text
    end = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end = i
            break
    if end is None:
        return None, text
    meta = {}
    for line in lines[1:end]:
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        m = re.match(r"^([A-Za-z0-9_-]+)\s*:\s*(.*)$", line)
        if not m:
            continue
        key, raw = m.group(1), m.group(2).strip()
        if len(raw) >= 2 and raw[0] == raw[-1] and raw[0] in "\"'":
            raw = raw[1:-1]
        meta[key] = raw
    body = "\n".join(lines[end + 1:]).lstrip("\n")
    return meta, body


def slugify(basename: str, division: str) -> str:
    slug = basename
    if slug.startswith(division + "-"):
        slug = slug[len(division) + 1:]
    return slug or basename


def title_case(label_source: str) -> str:
    return " ".join(w.capitalize() for w in re.split(r"[-_ ]+", label_source) if w)


# --------------------------------------------------------------------------- #
# Core generation
# --------------------------------------------------------------------------- #
def collect_agents(division_dir: Path):
    """Return sorted list of (path, meta, body) for agent files under a division."""
    agents = []
    for path in sorted(division_dir.rglob("*.md")):
        if path.name.lower() == "readme.md":
            continue
        text = path.read_text(encoding="utf-8")
        meta, body = parse_frontmatter(text)
        if not meta or "name" not in meta:
            continue
        agents.append((path, meta, body))
    return agents


def build_command_file(meta: dict, body: str) -> str:
    description = collapse_ws(meta.get("description", meta.get("name", "")))
    name = meta.get("name", "").strip()
    header = f"---\ndescription: {yaml_dq(description)}\n---\n"
    # The upstream body already carries its own H1; keep it verbatim so the
    # agent's personality/instructions survive the round-trip. Prepend a short
    # attribution line beneath the frontmatter.
    intro = (
        f"\n> Agency Agents specialist: **{name}**. "
        "Activate this agent for the task below.\n\n"
    )
    return header + intro + body.rstrip() + "\n"


def build_extension_yml(ext_id, ext_name, description, division, commands) -> str:
    lines = [
        'schema_version: "1.0"',
        "",
        "extension:",
        f"  id: {ext_id}",
        f"  name: {yaml_dq(ext_name)}",
        f'  version: "{VERSION}"',
        f"  description: {yaml_dq(description)}",
        f"  author: {AUTHOR}",
        f'  repository: "{REPOSITORY}"',
        "  license: MIT",
        f'  homepage: "{REPOSITORY}"',
        "",
        "requires:",
        f'  speckit_version: "{SPECKIT_REQUIRES}"',
        "",
        "provides:",
        "  commands:",
    ]
    for cmd in commands:
        lines.append(f"    - name: {cmd['name']}")
        lines.append(f"      file: {cmd['file']}")
        lines.append(f"      description: {yaml_dq(cmd['description'])}")
        lines.append("")
    lines.append("tags:")
    for tag in [PREFIX, "agents", division, "experimental"]:
        lines.append(f"  - {tag}")
    lines.append("")
    return "\n".join(lines)


def build_readme(ext_name, description, ext_id, division, label, commands) -> str:
    rows = "\n".join(f"| `/{c['name']}` | {c['agent_name']} |" for c in commands)
    return f"""# {ext_name}

{description}

> Agents in this extension are sourced from the
> [Agency Agents]({UPSTREAM_HOME}) collection (MIT) — the **{label}** division.
> Regenerate with the `{PREFIX}-sync` extension
> (`/speckit.{PREFIX}-sync.sync`).

## Installation

```bash
specify extension add {ext_id}
```

## Agents ({len(commands)})

| Command | Agent |
|---------|-------|
{rows}

## Usage

Invoke any agent command to load that specialist's personality and workflow,
then describe your task:

```
/{commands[0]['name']}
```
"""


def build_changelog(ext_name, count, date, label) -> str:
    return f"""# Changelog

All notable changes to the {ext_name} extension will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [{VERSION}] - {date}

### Added

- Initial release — {count} agent command(s) mirrored from the
  [Agency Agents]({UPSTREAM_HOME}) **{label}** division.
"""


def generate_division(division, label, division_dir: Path, repo_root: Path, date):
    agents = collect_agents(division_dir)
    if not agents:
        return None

    ext_id = f"{PREFIX}-{division}"
    ext_name = f"Agency Agents \u2014 {label}"
    description = (
        f"{label} division specialists from the Agency Agents collection "
        f"({len(agents)} agents)."
    )
    ext_dir = repo_root / ext_id
    commands_dir = ext_dir / "commands"

    # Clean previously generated commands so removed upstream agents disappear.
    if commands_dir.exists():
        shutil.rmtree(commands_dir)
    commands_dir.mkdir(parents=True, exist_ok=True)

    commands = []
    used_slugs = set()
    for path, meta, body in agents:
        slug = slugify(path.stem, division)
        if slug in used_slugs:
            slug = path.stem
        used_slugs.add(slug)
        cmd_file = f"commands/{slug}.md"
        (ext_dir / cmd_file).write_text(build_command_file(meta, body), encoding="utf-8")
        commands.append(
            {
                "name": f"speckit.{ext_id}.{slug}",
                "file": cmd_file,
                "description": collapse_ws(
                    meta.get("description", meta.get("name", ""))
                ),
                "agent_name": meta.get("name", slug).strip(),
            }
        )

    commands.sort(key=lambda c: c["name"])

    (ext_dir / "extension.yml").write_text(
        build_extension_yml(ext_id, ext_name, description, division, commands),
        encoding="utf-8",
    )
    (ext_dir / "README.md").write_text(
        build_readme(ext_name, description, ext_id, division, label, commands),
        encoding="utf-8",
    )
    (ext_dir / "CHANGELOG.md").write_text(
        build_changelog(ext_name, len(commands), date, label), encoding="utf-8"
    )

    return {
        "id": ext_id,
        "name": ext_name,
        "description": description,
        "division": division,
        "count": len(commands),
    }


# --------------------------------------------------------------------------- #
# catalog.json + README
# --------------------------------------------------------------------------- #
def catalog_entry(info):
    ext_id = info["id"]
    return {
        "name": info["name"],
        "id": ext_id,
        "version": VERSION,
        "description": info["description"],
        "author": AUTHOR,
        "repository": REPOSITORY,
        "download_url": f"{REPOSITORY}/releases/download/{ext_id}-v{VERSION}/{ext_id}.zip",
        "homepage": REPOSITORY,
        "documentation": f"{REPOSITORY}/blob/main/{ext_id}/README.md",
        "changelog": f"{REPOSITORY}/blob/main/{ext_id}/CHANGELOG.md",
        "license": "MIT",
        "requires": {"speckit_version": SPECKIT_REQUIRES},
        "provides": {"commands": info["count"], "hooks": 0},
        "tags": [PREFIX, "agents", info["division"], "experimental"],
    }


def update_catalog(repo_root: Path, infos, division_ids, date):
    catalog_path = repo_root / "catalog.json"
    catalog = json.loads(catalog_path.read_text(encoding="utf-8"))
    extensions = catalog.get("extensions", {})
    # Drop stale generated division extensions, keep everything else.
    for key in list(extensions):
        if key in division_ids:
            del extensions[key]
    for info in infos:
        extensions[info["id"]] = catalog_entry(info)
    catalog["extensions"] = {k: extensions[k] for k in sorted(extensions)}
    catalog["updated_at"] = date + "T00:00:00Z"
    catalog["catalog_url"] = RAW_CATALOG_URL
    catalog.setdefault("schema_version", "1.0")
    catalog_path.write_text(json.dumps(catalog, indent=2) + "\n", encoding="utf-8")


def update_readme(repo_root: Path, infos):
    readme_path = repo_root / "README.md"
    text = readme_path.read_text(encoding="utf-8")
    rows = "\n".join(
        f"| **[{i['id']}]({i['id']}/)** | {i['count']} | {i['description']} |"
        for i in sorted(infos, key=lambda x: x["id"])
    )
    block = (
        f"{README_BEGIN}\n\n"
        "### Agency Agents extensions\n\n"
        "Mirrored from the [Agency Agents](" + UPSTREAM_HOME + ") collection "
        "(MIT), one extension per division. Regenerate with the "
        "`agency-agents-sync` extension (`/speckit.agency-agents-sync.sync`).\n\n"
        "| Extension | Agents | Description |\n"
        "|-----------|--------|-------------|\n"
        f"{rows}\n\n"
        f"{README_END}"
    )
    if README_BEGIN in text and README_END in text:
        text = re.sub(
            re.escape(README_BEGIN) + r".*?" + re.escape(README_END),
            lambda _m: block,
            text,
            flags=re.DOTALL,
        )
    else:
        text = text.rstrip() + "\n\n" + block + "\n"
    readme_path.write_text(text, encoding="utf-8")


# --------------------------------------------------------------------------- #
# main
# --------------------------------------------------------------------------- #
def resolve_source(args, stack):
    if args.src:
        src = Path(args.src).expanduser().resolve()
        if not (src / "divisions.json").exists():
            sys.exit(f"error: {src} does not look like an agency-agents checkout")
        return src
    tmp = tempfile.mkdtemp(prefix="agency-agents-")
    stack.append(tmp)
    dest = Path(tmp) / "src"
    print(f"Cloning {UPSTREAM_URL} @ {args.ref} ...")
    subprocess.run(
        ["git", "clone", "--depth", "1", "--branch", args.ref, UPSTREAM_URL, str(dest)],
        check=True,
    )
    return dest


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ref", default="main", help="upstream git ref to clone")
    parser.add_argument(
        "--src", help="use a local agency-agents checkout instead of cloning"
    )
    parser.add_argument(
        "--repo-root",
        default=str(Path(__file__).resolve().parent.parent),
        help="target spec-kit-extensions repo root",
    )
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    date = _dt.date.today().isoformat()
    cleanup = []
    try:
        src = resolve_source(args, cleanup)
        divisions = json.loads(
            (src / "divisions.json").read_text(encoding="utf-8")
        )["divisions"]
        infos = []
        for division in sorted(divisions):
            label = divisions[division].get("label", title_case(division))
            division_dir = src / division
            if not division_dir.is_dir():
                print(f"  skip {division}: directory missing")
                continue
            info = generate_division(division, label, division_dir, repo_root, date)
            if info:
                print(f"  {info['id']}: {info['count']} agents")
                infos.append(info)

        division_ids = {f"{PREFIX}-{d}" for d in divisions}
        update_catalog(repo_root, infos, division_ids, date)
        update_readme(repo_root, infos)
        total = sum(i["count"] for i in infos)
        print(f"Done: {len(infos)} extensions, {total} agent commands.")
    finally:
        for tmp in cleanup:
            shutil.rmtree(tmp, ignore_errors=True)


if __name__ == "__main__":
    main()
